const fs = require('fs');
const nb = JSON.parse(fs.readFileSync('distillation_notebook.ipynb', 'utf8'));

// Update Cell 10 - Distillation Trainer with frequent checkpoints and robust resume
nb.cells[10].source = [
    "import os\n",
    "import torch\n",
    "import json\n",
    "import jsonlines\n",
    "from tqdm import tqdm\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import torch.nn.functional as F\n",
    "from torch.optim import AdamW\n",
    "\n",
    "if 'BASE_DIR' not in globals():\n",
    "    BASE_DIR = '/content/drive/MyDrive/svo cc brain'\n",
    "\n",
    "class RuleDataset(Dataset):\n",
    "    def __init__(self, path, tk):\n",
    "        print(f\"📖 Mapping Rule Dataset from: {path}\")\n",
    "        try:\n",
    "            from datasets import load_dataset\n",
    "            # Efficient lazy-loading using HuggingFace datasets library\n",
    "            self.data = load_dataset('json', data_files=path, split='train')\n",
    "        except Exception as e:\n",
    "            print(f\"❌ Failed to load dataset: {e}\")\n",
    "            raise e\n",
    "        self.tk = tk\n",
    "\n",
    "    def __len__(self): return len(self.data)\n",
    "\n",
    "    def __getitem__(self, i):\n",
    "        rule = self.data[i]\n",
    "        # Construct the distillation prompt\n",
    "        text = f\"Cause: {rule['cause']} -> Effect: {rule['effect']}\"\n",
    "        enc = self.tk(text, truncation=True, padding='max_length', max_length=128, return_tensors='pt')\n",
    "        return enc['input_ids'].squeeze(), enc['attention_mask'].squeeze()\n",
    "\n",
    "class DistillationTrainer:\n",
    "    def __init__(self, t, s, base_path):\n",
    "        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "        self.teacher = t\n",
    "        self.student = s\n",
    "        self.checkpoint_dir = os.path.join(base_path, \"checkpoints\")\n",
    "        os.makedirs(self.checkpoint_dir, exist_ok=True)\n",
    "        \n",
    "        self.opt = AdamW(self.student.parameters(), lr=4e-5)\n",
    "        self.step = 0\n",
    "        self._load_resume()\n",
    "\n",
    "    def _load_resume(self):\n",
    "        path = os.path.join(self.checkpoint_dir, \"latest_distill.pt\")\n",
    "        if os.path.exists(path):\n",
    "            print(f\"🔍 Found checkpoint: {path}. Resuming...\")\n",
    "            ckpt = torch.load(path, map_location='cpu')\n",
    "            self.student.load_state_dict(ckpt['model'])\n",
    "            self.opt.load_state_dict(ckpt['opt'])\n",
    "            self.step = ckpt.get('step', 0)\n",
    "            print(f\"✅ Resumed distillation from Step {self.step}\")\n",
    "        else:\n",
    "            print(\"🆕 No existing checkpoint found. Starting fresh.\")\n",
    "        \n",
    "        self.student.to(self.device)\n",
    "        # Re-initialize scheduler relative to current step\n",
    "        self.scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(self.opt, T_max=1000000, eta_min=1e-6)\n",
    "        if os.path.exists(path) and 'scheduler' in ckpt:\n",
    "            try:\n",
    "                self.scheduler.load_state_dict(ckpt['scheduler'])\n",
    "            except: pass\n",
    "\n",
    "    def save(self):\n",
    "        path = os.path.join(self.checkpoint_dir, \"latest_distill.pt\")\n",
    "        ckpt = {\n",
    "            'model': self.student.state_dict(), \n",
    "            'opt': self.opt.state_dict(), \n",
    "            'scheduler': self.scheduler.state_dict(),\n",
    "            'step': self.step\n",
    "        }\n",
    "        # Save Atomic to prevent file corruption during Colab session drop\n",
    "        torch.save(ckpt, path + \".tmp\")\n",
    "        os.replace(path + \".tmp\", path)\n",
    "        \n",
    "        if self.step % 5000 == 0:\n",
    "            torch.save(self.student.state_dict(), os.path.join(self.checkpoint_dir, f\"mure_3b_s{self.step}.pt\"))\n",
    "        \n",
    "        print(f\"💾 Checkpoint recorded at Step {self.step}\")\n",
    "\n",
    "    def train(self, loader):\n",
    "        self.teacher.eval()\n",
    "        self.student.train()\n",
    "        GRAD_ACCUM = 4\n",
    "        current_batch_in_epoch = self.step % len(loader)\n",
    "        \n",
    "        print(f\"🚀 Training stats: Total Batches={len(loader)}, Current Step={self.step}\")\n",
    "        pbar = tqdm(total=len(loader), initial=current_batch_in_epoch)\n",
    "        \n",
    "        for i, (input_ids, mask) in enumerate(loader):\n",
    "            # Sequential Resume Skip logic\n",
    "            if self.step > 0 and i < current_batch_in_epoch:\n",
    "                if i % 100 == 0: pbar.update(100)\n",
    "                continue\n",
    "            \n",
    "            ids, mask = input_ids.to(self.device), mask.to(self.device)\n",
    "            with torch.no_grad(): \n",
    "                t_logits = self.teacher(ids, attention_mask=mask).logits\n",
    "            \n",
    "            s_logits = self.student(ids, attention_mask=mask).logits\n",
    "            \n",
    "            # Standard KL-Divergence Loss for Distillation\n",
    "            batch, seq, vocab = s_logits.shape\n",
    "            loss = F.kl_div(F.log_softmax(s_logits.reshape(-1, vocab) / 2.0, dim=-1),\n",
    "                            F.softmax(t_logits.reshape(-1, vocab) / 2.0, dim=-1),\n",
    "                            reduction='batchmean') * 4.0\n",
    "            \n",
    "            (loss / GRAD_ACCUM).backward()\n",
    "            \n",
    "            if (i + 1) % GRAD_ACCUM == 0:\n",
    "                self.opt.step()\n",
    "                self.scheduler.step()\n",
    "                self.opt.zero_grad()\n",
    "            \n",
    "                self.step += 1\n",
    "                # FREQUENT CHECKPOINT: Every 200 optimization steps\n",
    "                if self.step % 200 == 0: \n",
    "                    self.save()\n",
    "            \n",
    "            if i % 10 == 0:\n",
    "                loss_val = loss.item() * GRAD_ACCUM # Real Loss\n",
    "                pbar.set_description(f\"Loss: {loss_val:.4f}\")\n",
    "            \n",
    "            pbar.update(1)\n",
    "        \n",
    "        self.save() # Save at end of epoch\n",
    "\n",
    "print(\"🚀 Initializing Knowledge Distillation Pipeline...\")\n",
    "dataset = RuleDataset(os.path.join(BASE_DIR, \"rules_synthetic_5M.jsonl\"), tokenizer)\n",
    "loader = DataLoader(dataset, batch_size=8, shuffle=False) # Shuffle False is CRITICAL for resume accuracy\n",
    "trainer = DistillationTrainer(teacher, student, BASE_DIR)\n",
    "\n",
    "print(f\"🔥 Distillation Active. Current Global Step: {trainer.step}\")\n",
    "trainer.train(loader)\n"
];

fs.writeFileSync('distillation_notebook.ipynb', JSON.stringify(nb, null, 1));
console.log('✅ Distillation Notebook synchronized and robustly patched.');
