const fs = require('fs');
const nb = JSON.parse(fs.readFileSync('distillation_notebook.ipynb', 'utf8'));

// Cell 1: ပိုပြီး robust ဖြစ်တဲ့ Drive Mount နဲ့ Directory Setup
nb.cells[1].source = [
    "## 1. Environment & Drive Setup (Required)\n",
    "from google.colab import drive\n",
    "import os\n",
    "\n",
    "# 1. Google Drive ကို အရင် Mount လုပ်မယ်\n",
    "if not os.path.exists('/content/drive'):\n",
    "    print(\"🔗 Connecting to Google Drive...\")\n",
    "    drive.mount('/content/drive')\n",
    "\n",
    "# 2. Path Setup - သင့်ရဲ့ Drive ထဲက folder path\n",
    "BASE_DIR = '/content/drive/MyDrive/svo cc brain'\n",
    "\n",
    "# 3. Folder မရှိရင် ဆောက်မယ်\n",
    "if not os.path.exists(BASE_DIR):\n",
    "    os.makedirs(BASE_DIR, exist_ok=True)\n",
    "    print(f\"📁 Created new workspace at: {BASE_DIR}\")\n",
    "else:\n",
    "    print(f\"✅ Using existing workspace at: {BASE_DIR}\")\n"
];

// Cell 2: Rule Generation (Resume only if missing)
nb.cells[2].source = [
    "!pip install -q jsonlines\n",
    "import os\n",
    "import jsonlines\n",
    "import random\n",
    "from tqdm import tqdm\n",
    "\n",
    "if 'BASE_DIR' not in globals():\n",
    "    BASE_DIR = '/content/drive/MyDrive/svo cc brain'\n",
    "\n",
    "RULES_FILE = os.path.join(BASE_DIR, 'rules_synthetic_5M.jsonl')\n",
    "TARGET_COUNT = 5_000_000\n",
    "\n",
    "rules_count = 0\n",
    "if os.path.exists(RULES_FILE):\n",
    "    print(\"🔍 Scanning existing rule file...\")\n",
    "    with open(RULES_FILE, 'r') as f:\n",
    "        for _ in f: rules_count += 1\n",
    "\n",
    "print(f\"📊 Existing Rules: {rules_count:,} / {TARGET_COUNT:,}\")\n",
    "\n",
    "if rules_count < TARGET_COUNT:\n",
    "    print(f\"⚡ Generating remaining {TARGET_COUNT - rules_count:,} rules...\")\n",
    "    # Ensure Directory exists before opening file\n",
    "    os.makedirs(os.path.dirname(RULES_FILE), exist_ok=True)\n",
    "    \n",
    "    def gen():\n",
    "        return {'cause': f\"Logic Node {random.random()}\", 'effect': f\"Outcome {random.random()}\"}\n",
    "    \n",
    "    with jsonlines.open(RULES_FILE, mode='a') as writer:\n",
    "        for _ in tqdm(range(TARGET_COUNT - rules_count)):\n",
    "            writer.write(gen())\n",
    "    print(\"✅ Rule Generation Task Finished.\")\n",
    "else:\n",
    "    print(\"✅ 5M Rules already present. Skipping generation.\")\n"
];

// Cell 10: Distillation Trainer with strictly frequent checkpoints
nb.cells[10].source = [
    "import os\n",
    "import torch\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import DataLoader\n",
    "from tqdm import tqdm\n",
    "\n",
    "# ... (Model loading logic remains same, assuming teacher/student/tokenizer available)\n",
    "\n",
    "class DistillationTrainer:\n",
    "    def __init__(self, t, s, base_path):\n",
    "        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "        self.teacher = t\n",
    "        self.student = s\n",
    "        self.checkpoint_dir = os.path.join(base_path, \"checkpoints\")\n",
    "        os.makedirs(self.checkpoint_dir, exist_ok=True)\n",
    "        \n",
    "        self.opt = torch.optim.AdamW(self.student.parameters(), lr=4e-5)\n",
    "        self.step = 0\n",
    "        self._load_resume()\n",
    "\n",
    "    def _load_resume(self):\n",
    "        path = os.path.join(self.checkpoint_dir, \"latest_distill.pt\")\n",
    "        if os.path.exists(path):\n",
    "            ckpt = torch.load(path, map_location='cpu')\n",
    "            self.student.load_state_dict(ckpt['model'])\n",
    "            self.opt.load_state_dict(ckpt['opt'])\n",
    "            self.step = ckpt.get('step', 0)\n",
    "            print(f\"⚡ Resuming from Step {self.step} (Found 2% progress or more)\")\n",
    "        self.student.to(self.device)\n",
    "\n",
    "    def save(self):\n",
    "        path = os.path.join(self.checkpoint_dir, \"latest_distill.pt\")\n",
    "        torch.save({'model': self.student.state_dict(), 'opt': self.opt.state_dict(), 'step': self.step}, path)\n",
    "        print(f\"💾 Progress saved at Step {self.step}\")\n",
    "\n",
    "    def train(self, loader):\n",
    "        self.teacher.eval()\n",
    "        self.student.train()\n",
    "        pbar = tqdm(total=len(loader), initial=self.step % len(loader))\n",
    "        \n",
    "        for i, (ids, mask) in enumerate(loader):\n",
    "            if self.step > 0 and i < (self.step % len(loader)): continue\n",
    "            \n",
    "            ids, mask = ids.to(self.device), mask.to(self.device)\n",
    "            with torch.no_grad(): t_logits = self.teacher(ids, attention_mask=mask).logits\n",
    "            s_logits = self.student(ids, attention_mask=mask).logits\n",
    "            \n",
    "            loss = F.kl_div(F.log_softmax(s_logits/2.0, dim=-1), F.softmax(t_logits/2.0, dim=-1), reduction='batchmean')\n",
    "            loss.backward()\n",
    "            self.opt.step()\n",
    "            self.opt.zero_grad()\n",
    "            \n",
    "            self.step += 1\n",
    "            # Update Checkpoint every 100 steps to prevent loss from Colab disconnection\n",
    "            if self.step % 100 == 0: self.save()\n",
    "            pbar.update(1)\n",
    "        self.save()\n",
    "\n",
    "trainer = DistillationTrainer(teacher, student, BASE_DIR)\n",
    "trainer.train(loader)\n"
];

fs.writeFileSync('distillation_notebook.ipynb', JSON.stringify(nb, null, 1));
console.log('✅ Synchronized with Google Drive and fixed path resolution.');
