const fs = require("fs");
const path = "distillation_notebook.ipynb";
const nb = JSON.parse(fs.readFileSync(path, "utf8"));

// Cell 3: Data gen flush
nb.cells[3].source = [
  "# 3. Robust Dataset Generation (5M Rules)\n",
  "RULES_FILE = os.path.join(BASE_DIR, \"rules_synthetic_5M.jsonl\")\n",
  "RULES_JSON_PATH = \"/data/brain/rules.json\"\n",
  "TARGET_COUNT = 5_000_000\n",
  "\n",
  "def load_rules():\n",
  "    with open(RULES_JSON_PATH, 'r') as f:\n",
  "        data = json.load(f)\n",
  "        return data.get('causalMemory', data) if isinstance(data, dict) else data\n",
  "\n",
  "rules = load_rules()\n",
  "def check_progress():\n",
  "    if not os.path.exists(RULES_FILE): return 0\n",
  "    with open(RULES_FILE, \"rb\") as f:\n",
  "        return sum(1 for _ in f)\n",
  "\n",
  "current_rules = check_progress()\n",
  "print(f\"📊 Current Progress: {current_rules:,} / {TARGET_COUNT:,}\")\n",
  "\n",
  "if current_rules < TARGET_COUNT:\n",
  "    print(\"⚡ Accelerating Generation...\")\n",
  "    TEMPLATES_QA = [\n",
  "        (\"What happens when {cause}?\", \"When {cause}, {effect}. (Confidence: {s:.2f})\"),\n",
  "        (\"What is the effect of {cause}?\", \"The effect is {effect}. (Strength: {s:.2f})\"),\n",
  "        (\"{cause} ဆိုတာ ဘာကိုဖြစ်စေသလဲ?\", \"{cause} ကြောင့် {effect} ဖြစ်ပေါ်သည်။\"),\n",
  "    ]\n",
  "    with open(RULES_FILE, \"a\", encoding=\"utf-8\") as f:\n",
  "        for idx, _ in enumerate(tqdm(range(TARGET_COUNT - current_rules), desc=\"Building Mind Space\")):\n",
  "            rule = random.choice(rules)\n",
  "            tmpl_q, tmpl_a = random.choice(TEMPLATES_QA)\n",
  "            s = rule.get(\"strength\", 0.8)\n",
  "            item = {\n",
  "                \"cause\": rule[\"cause\"], \"effect\": rule[\"effect\"],\n",
  "                \"strength\": s,\n",
  "                \"instruction\": tmpl_q.format(cause=rule[\"cause\"], effect=rule[\"effect\"]),\n",
  "                \"output\": tmpl_a.format(cause=rule[\"cause\"], effect=rule[\"effect\"], s=s)\n",
  "            }\n",
  "            f.write(json.dumps(item, ensure_ascii=False) + \"\\n\")\n",
  "            if idx % 10000 == 0:\n",
  "                f.flush()\n",
  "                os.fsync(f.fileno())\n",
  "print(\"✅ Knowledge Core Solidified.\")"
];

// Cell 5: KL-Distillation checkpointing and AMP fixes
nb.cells[5].source = [
  "# 5. Knowledge Distillation Engine (High-Performance KL-D)\n",
  "import os, torch, json\n",
  "import torch.nn.functional as F\n",
  "from torch.utils.data import DataLoader, Dataset\n",
  "from tqdm.auto import tqdm\n",
  "\n",
  "class HighSpeedDataset(Dataset):\n",
  "    def __init__(self, path, tk, limit=500000):\n",
  "        self.examples = []\n",
  "        if os.path.exists(path):\n",
  "            with open(path, \"r\") as f:\n",
  "                for i, line in enumerate(f):\n",
  "                    if i >= limit: break\n",
  "                    item = json.loads(line)\n",
  "                    self.examples.append(f\"Cause: {item['cause']} -> Effect: {item['effect']}\")\n",
  "        self.tk = tk\n",
  "    def __len__(self): return len(self.examples)\n",
  "    def __getitem__(self, i):\n",
  "        return self.tk(self.examples[i], truncation=True, padding=\"max_length\", max_length=128, return_tensors=\"pt\")\n",
  "\n",
  "loader = DataLoader(HighSpeedDataset(RULES_FILE, tokenizer), batch_size=8, shuffle=True)\n",
  "opt = torch.optim.AdamW(student.parameters(), lr=3e-5)\n",
  "use_bf16 = torch.cuda.is_bf16_supported()\n",
  "scaler = torch.cuda.amp.GradScaler(enabled=not use_bf16)\n",
  "\n",
  "trainer_state_path = os.path.join(BASE_DIR, \"distill_state.pt\")\n",
  "start_batch = 0\n",
  "if os.path.exists(trainer_state_path):\n",
  "    state = torch.load(trainer_state_path)\n",
  "    # Avoid strict loading since bitsandbytes layers might differ slightly on dict export\n",
  "    student.load_state_dict(state['model'], strict=False)\n",
  "    opt.load_state_dict(state['optimizer'])\n",
  "    start_batch = state['batch']\n",
  "    print(f\"🔄 Resuming from batch {start_batch}\")\n",
  "\n",
  "dtype = torch.bfloat16 if use_bf16 else torch.float16\n",
  "\n",
  "for i, batch in enumerate(tqdm(loader, desc=\"Distilling Knowledge (KL-Loss)\")):\n",
  "    if i < start_batch: continue\n",
  "    ids = batch['input_ids'].squeeze(1).cuda()\n",
  "    \n",
  "    with torch.cuda.amp.autocast(dtype=dtype):\n",
  "        with torch.no_grad(): t_logits = teacher(ids).logits\n",
  "        s_logits = student(ids).logits\n",
  "        \n",
  "        B, T, V = s_logits.size()\n",
  "        vm = min(s_logits.size(-1), t_logits.size(-1))\n",
  "        \n",
  "        s_flat = F.log_softmax(s_logits[..., :vm].reshape(-1, vm).float() / 2.0, dim=-1)\n",
  "        t_flat = F.softmax(t_logits[..., :vm].reshape(-1, vm).float() / 2.0, dim=-1)\n",
  "        \n",
  "        loss = F.kl_div(s_flat, t_flat, reduction=\"batchmean\") * 4.0\n",
  "    \n",
  "    if use_bf16:\n",
  "        loss.backward()\n",
  "        if (i+1) % 4 == 0: opt.step(); opt.zero_grad()\n",
  "    else:\n",
  "        scaler.scale(loss).backward()\n",
  "        if (i+1) % 4 == 0: scaler.step(opt); scaler.update(); opt.zero_grad()\n",
  "        \n",
  "    if (i + 1) % 1000 == 0:\n",
  "        torch.save({'model': student.state_dict(), 'optimizer': opt.state_dict(), 'batch': i + 1}, trainer_state_path)\n"
];

// Cell 6: DPO alignment
nb.cells[6].source = [
  "# 6. DPO Alignment (Direct Preference Optimization)\n",
  "print(\"⚖️ Starting DPO Alignment...\")\n",
  "from trl import DPOConfig, DPOTrainer\n",
  "from datasets import Dataset as HFDataset\n",
  "from peft import LoraConfig, get_peft_model\n",
  "import json\n",
  "\n",
  "lora_cfg = LoraConfig(r=16, lora_alpha=32, target_modules=[\"q_proj\",\"k_proj\",\"v_proj\",\"o_proj\"], lora_dropout=0.05, bias=\"none\", task_type=\"CAUSAL_LM\")\n",
  "student_dpo = get_peft_model(student, lora_cfg)\n",
  "\n",
  "with open(os.path.join('/data/brain', \"rules.json\"), \"r\") as f:\n",
  "    raw_rules = json.load(f)\n",
  "rules_list = raw_rules.get(\"causalMemory\", raw_rules) if isinstance(raw_rules, dict) else raw_rules\n",
  "\n",
  "prompts, chosen_list, rejected_list = [], [], []\n",
  "for rule in rules_list[:500]:\n",
  "    cause = rule.get(\"cause\", \"\")\n",
  "    effect = rule.get(\"effect\", \"\")\n",
  "    s = rule.get(\"strength\", 0.8)\n",
  "    if not cause or not effect: continue\n",
  "    prompts.append(f\"What happens when {cause}?\")\n",
  "    chosen_list.append(f\"{cause} leads to {effect}. This occurs with confidence {s:.2f}.\")\n",
  "    rejected_list.append(\"Something happens. I'm not sure what exactly.\")\n",
  "\n",
  "preference_data = {\"prompt\": prompts, \"chosen\": chosen_list, \"rejected\": rejected_list}\n",
  "dpo_ds = HFDataset.from_dict(preference_data)\n",
  "print(f\"📊 DPO Dataset Size: {len(dpo_ds)} samples\")\n",
  "\n",
  "dpo_config = DPOConfig(\n",
  "    output_dir=os.path.join(BASE_DIR, \"dpo_checkpoints\"), num_train_epochs=3,\n",
  "    per_device_train_batch_size=1, gradient_accumulation_steps=4,\n",
  "    learning_rate=5e-7, beta=0.1, report_to=\"none\",\n",
  "    bf16=torch.cuda.is_bf16_supported(), fp16=not torch.cuda.is_bf16_supported(),\n",
  "    logging_steps=5\n",
  ")\n",
  "\n",
  "dpo_trainer = DPOTrainer(\n",
  "    model=student_dpo,\n",
  "    ref_model=None,\n",
  "    args=dpo_config,\n",
  "    train_dataset=dpo_ds,\n",
  "    tokenizer=tokenizer,\n",
  ")\n",
  "\n",
  "dpo_trainer.train()\n",
  "print(\"✅ DPO Alignment complete!\")\n"
];

fs.writeFileSync(path, JSON.stringify(nb, null, 1));
