const fs = require('fs');
const nb = JSON.parse(fs.readFileSync('distillation_notebook.ipynb', 'utf8'));

// Update Cell 10 for fp16 mixed precision and larger batch
nb.cells[10].source = [
    "# 5. Knowledge Distillation Engine (Accelerated with FP16)\n",
    "import os, torch, torch.nn.functional as F\n",
    "from torch.utils.data import DataLoader, Dataset\n",
    "from tqdm import tqdm\n",
    "from torch.optim import AdamW\n",
    "from torch.amp import autocast, GradScaler\n",
    "\n",
    "if 'BASE_DIR' not in globals():\n",
    "    BASE_DIR = '/content/drive/MyDrive/svo cc brain'\n",
    "    \n",
    "class RuleDataset(Dataset):\n",
    "    def __init__(self, path, tk):\n",
    "        try:\n",
    "            from datasets import load_dataset\n",
    "            self.data = load_dataset('json', data_files=path, split='train')\n",
    "        except:\n",
    "            self.data = []\n",
    "        self.tk = tk\n",
    "    def __len__(self): return len(self.data)\n",
    "    def __getitem__(self, i):\n",
    "        rule = self.data[i]\n",
    "        text = f\"Cause: {rule['cause']} -> Effect: {rule['effect']}\"\n",
    "        e = self.tk(text, truncation=True, padding='max_length', max_length=128, return_tensors='pt')\n",
    "        return e['input_ids'].squeeze(), e['attention_mask'].squeeze()\n",
    "\n",
    "class DistillationTrainer:\n",
    "    def __init__(self, t, s, base_path):\n",
    "        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "        self.teacher = t\n",
    "        self.student = s.to(self.device)\n",
    "        self.checkpoint_dir = os.path.join(base_path, \"checkpoints\")\n",
    "        os.makedirs(self.checkpoint_dir, exist_ok=True)\n",
    "        self.opt = AdamW(self.student.parameters(), lr=1e-4) # Slightly higher LR for speed\n",
    "        self.step = 0\n",
    "        self.scaler = GradScaler(self.device)\n",
    "        self._load_resume()\n",
    "\n",
    "    def _load_resume(self):\n",
    "        path = os.path.join(self.checkpoint_dir, \"latest_distill.pt\")\n",
    "        if os.path.exists(path):\n",
    "            ckpt = torch.load(path, map_location='cpu')\n",
    "            self.student.load_state_dict(ckpt['model'])\n",
    "            self.opt.load_state_dict(ckpt['opt'])\n",
    "            self.step = ckpt.get('step', 0)\n",
    "            print(f\"✅ Resumed at Step {self.step}\")\n",
    "\n",
    "    def save(self):\n",
    "        path = os.path.join(self.checkpoint_dir, \"latest_distill.pt\")\n",
    "        torch.save({'model': self.student.state_dict(), 'opt': self.opt.state_dict(), 'step': self.step}, path + \".tmp\")\n",
    "        os.replace(path + \".tmp\", path)\n",
    "        print(f\"💾 Saved Step {self.step}\")\n",
    "\n",
    "    def train(self, loader):\n",
    "        self.teacher.eval()\n",
    "        self.student.train()\n",
    "        GRAD_ACCUM = 8\n",
    "        start_idx = self.step % len(loader)\n",
    "        pbar = tqdm(total=len(loader), initial=start_idx)\n",
    "        for i, (ids, mask) in enumerate(loader):\n",
    "            if self.step > 0 and i < start_idx:\n",
    "                if i % 100 == 0: pbar.update(100)\n",
    "                continue\n",
    "            \n",
    "            ids, mask = ids.to(self.device), mask.to(self.device)\n",
    "            \n",
    "            # ======== Mixed Precision ======== \n",
    "            with autocast(device_type=self.device, dtype=torch.float16):\n",
    "                with torch.no_grad(): t_logits = self.teacher(ids, attention_mask=mask).logits\n",
    "                s_logits = self.student(ids, attention_mask=mask).logits\n",
    "                loss = F.kl_div(F.log_softmax(s_logits/2.0, dim=-1), F.softmax(t_logits/2.0, dim=-1), reduction='batchmean')\n",
    "            \n",
    "            self.scaler.scale(loss / GRAD_ACCUM).backward()\n",
    "            \n",
    "            if (i + 1) % GRAD_ACCUM == 0:\n",
    "                self.scaler.step(self.opt)\n",
    "                self.scaler.update()\n",
    "                self.opt.zero_grad()\n",
    "                self.step += 1\n",
    "                if self.step % 100 == 0: self.save()\n",
    "            \n",
    "            if i % 10 == 0: pbar.set_description(f\"Step {self.step} | Loss: {loss.item():.4f}\")\n",
    "            pbar.update(1)\n",
    "        self.save()\n",
    "\n",
    "print(\"🚀 Starting Accelerated FP16 Distillation...\")\n",
    "dataset = RuleDataset(os.path.join(BASE_DIR, \"rules_synthetic_5M.jsonl\"), tokenizer)\n",
    "# Using batch_size=16 for acceleration due to fp16 saving memory\n",
    "loader = DataLoader(dataset, batch_size=16, shuffle=False)\n",
    "trainer = DistillationTrainer(teacher, student, BASE_DIR)\n",
    "trainer.train(loader)\n"
];

fs.writeFileSync('distillation_notebook.ipynb', JSON.stringify(nb, null, 1));
console.log('✅ Distillation Notebook accelerated with torch.amp.autocast and bs=16.');
